### ISSUE TITLE
Index page is in English

### ISSUE THREAD

**Issue by agriffard** [aspnet/Docs.fr-fr#203] opened 2019-03-21 16:18 UTC
The start page is in English: https://docs.microsoft.com/fr-fr/aspnet/

The first page people can navigate to should be in their language.

The other products seem to have a homepage translated.

Is there any Index page that I can help to localize?

**Comment by CeciAc** [comment] 2019-03-21 17:10
Hello, @agriffard 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment] 2019-03-21 17:12
Hi @JasonCard 
Its the same with the other locales
best

**Comment by JasonCard** [comment] 2019-03-21 19:28
Hi @agriffard, thank you for reporting this issue. It was previously translated, but was temporarily falling back to English. The issue is now fixed and displaying translated content.
cc @CeciAc

**Closed by JasonCard** 2019-03-21 19:28 UTC
Labels: Linguistic Suggestion
